// import React, { createContext, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

import { AppContext } from '../Context/appContext';
// import {
//     getLanguageList,
// } from '../api';
// //let LanguageData1;
// export const LanguageData = async () => {
//     let lang = JSON.parse(await AsyncStorage.getItem('language'));
//     //LanguageData1 = lang;
//     return lang;

// }

// export class User {
//     LanguageData = async () => {
//         let lang = JSON.parse(await AsyncStorage.getItem('language'));
//         //LanguageData1 = lang;
//         return lang;

//     }

// }


const LanguageData = {
    en: {
        SomethingWentWrong: "Something went wrong",
        EnterAValidMobileNumber: "Enter a valid mobile number",
        Required: "Required",
        CountryListIsEmpty: "Country list is empty",
        StateListIsEmpty: "State list is empty",
        DistrictListIsEmpty: "District list is empty",
        __language: "Language",
        _forward: "Forward",
        welcome: "Welcome",
        TodaysDeal: "TODAY'S DEAL",
        ViewAll: "View all",
        PopularProducts: "POPULAR PRODUCTS",
        RecentlyViewedProducts: "RECENTLY VIEWED PRODUCTS",
        State: "STATE",
        City: "District / City",
        Country: "COUNTRY",
        ShipOrBill: "ship / bill",
        AddressAdded: "Address added",
        MyAddresses: "My Addresses",
        FirstName: "FIRST NAME",
        LastName: "LAST NAME",
        AddressLine1: "ADDRESS LINE 1",
        AddressLine2: "ADDRESS LINE 2",
        Phone: "PHONE",
        Pincode: "PINCODE",
        Landmark: "LANDMARK",
        MakeAsDefaultShippingAddress: "MAKE AS DEFAULT SHIPPING ADDRESS",
        MakeAsDefaultBillingAddress: "MAKE AS DEFAULT BILLING ADDRESS",
        Update: "Update",
        Save: "Save",
        SelectACountry: "Select a Country",
        Search: "Search",
        SelectAState: "Select a State",
        SelectACityOrDistrict: "Select a City / District",
        MyAddressEmpty: "MY ADDRESS EMPTY !",
        AddNew: "ADD NEW",
        Default: "DEFAULT",
        MakeDefault: "MAKE DEFAULT",
        ShippingOrBilling: "Shipping / Billing",
        Billing: "Billing",
        Shipping: "Shipping",
        CouponFieldEmpty: "Coupon Field Empty",
        CouponAdded: "Coupon Added",
        Cart: "Cart",
        CartEmpty: "CART EMPTY !",
        CartEmptyDescription: "It is a Long Established fact that a Reader will be distracted by the readable content",
        Browse: "BROWSE",
        CartWarning: "Remove the item from cart?",
        Cancel: "Cancel",
        CancelPressed: "Cancel Pressed",
        OK: "OK",
        CouponCode: "COUPON CODE :",
        Apply: "APPLY",
        Subtotal: "Subtotal",
        Discount: "Discount",
        CouponDiscount: "Coupon Discount",
        Total: "Total",
        SelectAddress: "SELECT ADDRESS",
        Login: "Login",
        CurrencySymbol: "₹",
        PopularProducts: "Popular Products",
        NoResultsFound: "NO RESULTS FOUND",
        Minimum6CharactersRequired: "minimum 6 characters required for new password",
        PleaseConfirmPassword: "Please Confirm Password",
        PasswordChangedSuccessfully: "Password Changed Successfully",
        ChangePassword: "Change Password",
        NewPassword: "New Password",
        ConfirmPassword: "Confirm Password",
        ChangePassword: "Change Password",
        CanotUseCurrentPassword: "Canot use current password",
        PasswordDoesnotMatch: "Password doesn't match",
        OldPassword: "Old Password",
        Coupons: "Coupons",
        CouponsEmpty: "COUPONS EMPTY !",
        DealOfTheDay: "Deal Of The Day",
        DealOfTheDayEmpty: "DEAL OF THE DAY EMPTY !",
        AddedToWishlist: "Added to wishlist",
        RemovedFromWishlist: "Removed From Wishlist",
        UrlKeyIsNull: "UrlKey is null",
        AddedToCart: "Added To Cart",
        RemovedFromCart: "Removed From Cart",
        EmailIDAlreadyInUse: "Email ID already in use.",
        PhoneNumberAlreadyInUse: "Phone number already in use.",
        DetailsAreNotChanged: "Details are not changed",
        ProfileUpdatedSuccessfull: "Profile Updated Successfull",
        EditProfile: "Edit Profile",
        UserName: "USER NAME*",
        EmailID: "EMAIL ID*",
        Mobile: "MOBILE*",
        Password: "PASSWORD*",
        Update: "UPDATE",
        SentOTPToYourDevice: "SENT OTP TO YOUR DEVICE",
        EnterOTP: "Enter OTP :",
        OTPSent: "OTP sent",
        AlreadyHaveAnAccount: "Already have an account ?",
        ResendOTP: "Resend OTP",
        Categories: "Categories",
        PriceRange: "Price Range",
        TroubleLoggingIn: "Trouble Logging in ..?",
        ForgotPasswordDescription: "Reset Your Password to access thousands of products",
        EmailIdOrMobileNumber: "EMAIL ID / MOBILE NUMBER",
        SentOTP: "Send OTP",
        LatestArrival: "Latest Arrival",
        LatestArrivalEmpty: "LATEST ARRIVALS EMPTY !",
        ForgotPassword: "Forgot Password ?",
        DonotHaveAnAccount: "Don't have an account?",
        RegisterNow: "Register Now",
        NoProductsFound: "No products found !",
        BrowseMore: "Browse More",
        MyOrders: "My Orders",
        MyOrdersEmpty: "MY ORDERS EMPTY !",
        ViewAllOrders: "View All Orders",
        OrderConfirmation: "Order Confirmation",
        YourOrderReceived: "Your Order has been Received",
        YourOrder: "Your Order",
        OrderDescription: "You will Receive an order confirmation email with details of your order & a link to track its Progress.",
        ContinueShopping: "Continue Shopping",
        Payment: "Payment",
        PersonalInfo: "Personal Info",
        ShippingAddress: "Shipping Address",
        PaymentMethods: "Payment Methods",
        COD: "COD",
        PlaceOrder: "PLACE ORDER",
        ChangeAddress: "CHANGE ADDRESS",
        Back: "Back",
        Profile: "Profile",
        Wishlist: "Wishlist",
        MyAddress: "My Address",
        Support: "Support",
        Logout: "Logout",
        AreYouSureWantToLogout: "Are you sure want to logout?",
        EnterValidMailID: "Enter valid mail id",
        MobileNumberAlreadyExists: "Mobile Number Already Exists",
        AgreeTermsAndConditions: "Agree Terms and Conditions",
        CreateNewAccountDescription: "Create a New Account to access thousands of products",
        Password: "PASSWORD*",
        TermsOfUse: "Terms of Use",
        SignUp: "Sign Up",
        Reviews: "Reviews",
        AddtionalTax: "Addtional tax shall be apply.Charged at checkout",
        AllReviews: "All Reviews",
        PleaseLoginForWriteReview: "Please Login for write Review",
        WriteAReview: "Write a Review",
        OutOf5: "Out of 5",
        Filter: "FILTER",
        Clear: "CLEAR",
        NoProductsAvailableForThisPincode: "No products are available for this pincode currently",
        ResetYourPasswordToAccessThousandsOfProducts: "Reset Your Password to access thousands of products",
        NEWPASSWORD: "NEW PASSWORD*",
        CONFIRMPASSWORD: "CONFIRM PASSWORD*",
        SetNewPassword: "SET NEW PASSWORD",
        ProductDetails: "Product Details",
        SoldBy: "Sold by:",
        ShortDescription: "Short Description",
        OutOfStock: "OUT OF STOCK",
        GoToCart: " Go to Cart",
        AddToCart: "Add to Cart",
        StoragePermissionRequired: "Storage Permission Required",
        StoragePermissionDescription: "This app needs access to your storage to download Documents",
        StoragePermissionNotGranted: "Storage Permission Not Granted",
        DownloadCompleted: "Download Completed",
        DownloadingFileName: "/PitchKart_Invoice_",
        OrderDetails: "Order Details",
        OrderNo: "Order # :",
        DateTag: "Date :",
        OrderTotal: "RDER TOTAL : ",
        CurrencyValue: "INR",
        DownloadInvoice: "Download Invoice",
        TrackShipment: "Track Shipment",
        Explore: "Explore",
        TopSellers: "Top Sellers",
        TopSellerEmpty: "TOP SELLERS EMPTY !",
        WishListEmpty: "WISH LIST EMPTY !",
        Today: "Today",
        EnterAllFields: "Enter All Fields",
        Title: "Title",
        WriteYourReview: "Write Your Review",
        MaximumCharacters: "Maximum Characters : 250",
        Submit: "Submit",
        CheckAgree: "Check Agree.",
        NewSupportRequestAdded: "New Support Request added.",
        WriteToUs: "Write To Us",
        Message: "MESSAGE",
        SendMessage: "SEND MESSAGE",
        Agree: "AGREE",
        AccountCreatedSuccessfully: "Account created successfully",
        LoginSuccessfully: "logged in successfully",
        LogOutSuccessfully: "logged out successfully",
        NetworkError: "Network Error. Ensure you are connected to internet.",
        ServerIsNotResponding: "Server is not responding",
        SomethingWentWrong: "Something went wrong.",
        ShopNow: "Shop Now",
        MoveToCart: "MOVE TO CART",
        Off: "% OFF",
        CurrencyCode: "Rs.",
        MoreItems: "more item(s)",
        Quantity: "QTY :",
        Invoice: "Invoice",
        Change: "CHANGE",
        ChangePincode: "Change Pincode",
        DeliveryNotAvailable: "Delivery Not Available"
    }
};
export default LanguageData;